use crate::{HOMEPAGE, NAME, VERSION, conventions::conventional::builder::ConventionalFooter};

pub fn get_commit_msg_footer () -> String {
  ConventionalFooter::new(
    Some(
      format!("Generated by {} {} — Check it out at: {}", NAME, VERSION, HOMEPAGE)
    ),
    Some(false)
  ).to_string()
}
