use crate::{HOMEPAGE, NAME, VERSION, config::Config, conventions::{config::{ConvetionTypes, DEFAULT_CONVENTION}, conventional::{builder::{ConventionalBuilder, ConventionalFooter, ConventionalHeader}, types::Types}}};

pub fn get_conventional_commit_msg () -> String {
  let conventional_header = ConventionalHeader::new(
    Some(Types::Chore),
    Some("changelog".to_string()),
    Some("update changelog".to_string()),
    Some(false)
  );
  let conventional_footer = ConventionalFooter::new(
    Some(
      format!("Generated by {} {} — Check it out at: {}", NAME, VERSION, HOMEPAGE)
    ),
    Some(false)
  );

  return ConventionalBuilder::new(
    Some(conventional_header.to_string()),
    None,
    Some(vec![conventional_footer.to_string()])
  ).to_string();
}

pub fn get_commit_msg () -> String {
  let config = Config::inject();

  let convention = config.convention.as_ref().unwrap_or(&DEFAULT_CONVENTION);

  match convention {
    ConvetionTypes::Conventional => get_conventional_commit_msg()
  }
}
